### ISSUE TITLE
Standard Footer

### ISSUE THREAD

**Issue by afridihannan** [CodeFlow201/Team-3#12]

**Comment by AravindHari** [comment]
@afridihannan Please assign me this task

**Comment by afridihannan** [comment]
@AravindHari  Please Proceed

**Comment by AravindHari** [comment]
Hey, can you please specify the requirements of the footer?
can it be a basic HTML/CSS kind?

**Comment by afridihannan** [comment]
No, it will be in React JS (jsx) and type of the footer ...You can just refer to Internet for some standard Footer

**Comment by NarayanAdithya** [comment]
@afridihannan , Is there a reason the issue is closed? Since I don't see any PR solving the issue.

**Comment by afridihannan** [comment]
Ya @NarayanAdithya  This issue has been closed. You can look for modifying the UI👍🏻👍🏻

**Comment by AravindHari** [comment]
@afridihannan do I need to work on it? I have been assigned this task and I am working on it

**Comment by afridihannan** [comment]
@AravindHari  Go ahead and try to modify the other UI too
